[".dotfiles/vim/bundle/lightline.vim"]
    type = "archive"
    url = "https://github.com/itchyny/lightline.vim/archive/d6a07ea376a4b7372aa59e7ea6a051c9470bb4d0.tar.gz"
    exact = true
    stripComponents = 1

[".dotfiles/vim/bundle/nerdcommenter"]
    type = "archive"
    url = "https://github.com/preservim/nerdcommenter/archive/66c07e4083ab02ed2540ac289cc602c70b858c13.tar.gz"
    exact = true
    stripComponents = 1

[".dotfiles/vim/bundle/nerdtree"]
    type = "archive"
    url = "https://github.com/preservim/nerdtree/archive/9b465acb2745beb988eff3c1e4aa75f349738230.tar.gz"
    exact = true
    stripComponents = 1

[".dotfiles/vim/bundle/vim-colors-solarized"]
    type = "archive"
    url = "https://github.com/altercation/vim-colors-solarized/archive/528a59f26d12278698bb946f8fb82a63711eec21.tar.gz"
    exact = true
    stripComponents = 1

[".dotfiles/vim/bundle/vim-cpp-modern"]
    type = "archive"
    url = "https://github.com/bfrg/vim-cpp-modern/archive/e8d916e7addb132d96691252bbae22a57fea0c41.tar.gz"
    exact = true
    stripComponents = 1

[".dotfiles/zsh/plugins/zsh-completions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-completions/archive/c160d09fddd28ceb3af5cf80e9253af80e450d96.tar.gz"
    exact = true
    stripComponents = 1

[".dotfiles/zsh/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/1715f39a4680a27abd57fc30c98a95fdf191be45.tar.gz"
    exact = true
    stripComponents = 1

[".dotfiles/zsh/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/ae315ded4dba10685dbbafbfa2ff3c1aefeb490d.tar.gz"
    exact = true
    stripComponents = 1

[".dotfiles/shell/plugins/dircolors-solarized"]
    type = "archive"
    url = "https://github.com/seebi/dircolors-solarized/archive/2249310a957977e523b62c7d916ba40c2165869c.tar.gz"
    exact = true
    stripComponents = 1

# ZSH plugins

[".dotfiles/zsh/plugins/fzf"]
    type = "archive"
    url = "https://github.com/junegunn/fzf/archive/50be8bc78e1b22d51bbb35069e361ae8027e68b4.tar.gz"
    exact = true
    stripComponents = 1

[".dotfiles/zsh/plugins/fzf-tab"]
    type = "archive"
    url = "https://github.com/Aloxaf/fzf-tab/archive/0fbd5753f935dcb6899e5fb2a0fb9a3fd69f1ce0.tar.gz"
    exact = true
    stripComponents = 1

[".dotfiles/zsh/plugins/zsh-history-substring-search"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-history-substring-search/archive/14c8d2e0ffaee98f2df9850b19944f32546fdea5.tar.gz"
    exact = true
    stripComponents = 1

[".dotfiles/zsh/plugins/zsh-autopair"]
    type = "archive"
    url = "https://github.com/hlissner/zsh-autopair/archive/449a7c3d095bc8f3d78cf37b9549f8bb4c383f3d.tar.gz"
    exact = true
    stripComponents = 1

[".dotfiles/zsh/plugins/fzf-git.sh"]
    type = "archive"
    url = "https://github.com/junegunn/fzf-git.sh/archive/34cd6c9d315d9b59b94721bd602c5769e919d686.tar.gz"
    exact = true
    stripComponents = 1

[".dotfiles/zsh/plugins/zsh-you-should-use"]
    type = "archive"
    url = "https://github.com/MichaelAquilina/zsh-you-should-use/archive/ff371d6a11b653e1fa8dda4e61c896c78de26bfa.tar.gz"
    exact = true
    stripComponents = 1

# Vim plugins

[".dotfiles/vim/bundle/vim-fugitive"]
    type = "archive"
    url = "https://github.com/tpope/vim-fugitive/archive/61b51c09b7c9ce04e821f6cf76ea4f6f903e3cf4.tar.gz"
    exact = true
    stripComponents = 1

[".dotfiles/vim/bundle/vim-surround"]
    type = "archive"
    url = "https://github.com/tpope/vim-surround/archive/3d188ed2113431cf8dac77be61b842acb64433d9.tar.gz"
    exact = true
    stripComponents = 1

[".dotfiles/vim/bundle/fzf.vim"]
    type = "archive"
    url = "https://github.com/junegunn/fzf.vim/archive/34a564c81f36047f50e593c1656f4580ff75ccca.tar.gz"
    exact = true
    stripComponents = 1

[".dotfiles/vim/bundle/ale"]
    type = "archive"
    url = "https://github.com/dense-analysis/ale/archive/69c945d5daecadf8e4c4c499d0a7babda748d603.tar.gz"
    exact = true
    stripComponents = 1

[".dotfiles/vim/bundle/vim-gitgutter"]
    type = "archive"
    url = "https://github.com/airblade/vim-gitgutter/archive/0acb772e76064cc406664ab595b58b3fac76488a.tar.gz"
    exact = true
    stripComponents = 1

[".dotfiles/vim/bundle/vim-repeat"]
    type = "archive"
    url = "https://github.com/tpope/vim-repeat/archive/65846025c15494983dafe5e3b46c8f88ab2e9635.tar.gz"
    exact = true
    stripComponents = 1

[".dotfiles/vim/bundle/undotree"]
    type = "archive"
    url = "https://github.com/mbbill/undotree/archive/d8f99084d98c32f651860eb0baaf89759f91debc.tar.gz"
    exact = true
    stripComponents = 1

[".dotfiles/vim/bundle/vim-polyglot"]
    type = "archive"
    url = "https://github.com/sheerun/vim-polyglot/archive/f061eddb7cdcc614c8406847b2bfb53099832a4e.tar.gz"
    exact = true
    stripComponents = 1

# Tmux Plugin Manager

[".dotfiles/tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/99469c4a9b1ccf77fade25842dc7bafbc8ce9946.tar.gz"
    exact = true
    stripComponents = 1
